name: workflow to deploy an ARM Template to a resource group
on: 
  push:
    branches: 
      - master
    paths:
      - 'infrastructure/**'

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

env:
  AZURE_RESOURCE_GROUP: gh-accelerator   # set this to your Azure Resource group's name  
  AZURE_WEBAPP_NAME: node-gh-accelerator # set this to your Azure Web App's name  
  
jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
                
    # Authentication
    # Set up the following secrets in your repository: AZURE_CREDENTIALS
    # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
        
    # Deployment of template    
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: infrastructure/azuredeploy.json  # Set this to the location of your template file
        parameters: infrastructure/azuredeploy.parameters.json webappname=${{ env.AZURE_WEBAPP_NAME }} subscriptionId=${{ secrets.AZURE_SUBSCRIPTION_ID }} 
